# Generated by Django 5.2.6 on 2026-10-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.category'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.employee'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Retired', 'Retired')], default='Open', max_length=20),
        ),
    ]
